import type { NextApiRequest, NextApiResponse } from "next";
import { google } from "googleapis";
import { Resend } from "resend";

type ResponseData = {
  success: boolean;
  message: string;
};

const resend = new Resend(process.env.RESEND_API_KEY);

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse<ResponseData>
) {
  if (req.method !== "POST") {
    return res.status(405).json({
      success: false,
      message: "Method not allowed",
    });
  }

  try {
    const {
      product,
      name,
      phone,
      whatsapp,
      state,
      city,
      address,
      quantity,
      note,
    } = req.body;

    // Basic validation
    if (
      !product ||
      !name ||
      !phone ||
      !state ||
      !city ||
      !address ||
      !quantity
    ) {
      return res.status(400).json({
        success: false,
        message: "Please fill in all required fields.",
      });
    }

    // =========================
    // GOOGLE SHEETS
    // =========================

    const auth = new google.auth.GoogleAuth({
      credentials: {
        client_email: process.env.GOOGLE_CLIENT_EMAIL,
        private_key: process.env.GOOGLE_PRIVATE_KEY?.replace(/\\n/g, "\n"),
      },
      scopes: [
        "https://www.googleapis.com/auth/spreadsheets",
      ],
    });

    const sheets = google.sheets({
      version: "v4",
      auth,
    });

    // Add order to Google Sheet
    await sheets.spreadsheets.values.append({
      spreadsheetId: process.env.GOOGLE_SHEET_ID,
      range: "Sheet1!A:K",
      valueInputOption: "USER_ENTERED",
      requestBody: {
        values: [
          [
            new Date().toLocaleString("en-NG", {
              timeZone: "Africa/Lagos",
            }),
            product,
            name,
            phone,
            whatsapp || "",
            state,
            city,
            address,
            quantity,
            note || "",
            "Pending",
          ],
        ],
      },
    });

    // =========================
    // EMAIL NOTIFICATION
    // =========================

    await resend.emails.send({
      from: "StarnTech Orders <onboarding@resend.dev>",
      to: process.env.ORDER_NOTIFICATION_EMAIL!,
      subject: `🛒 New Order - ${product}`,
      html: `
        <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #222;">
          
          <h2 style="color: #15803d;">
            🛒 New StarnTech Order
          </h2>

          <p>A new order has been submitted from your website.</p>

          <hr />

          <h3>Product Details</h3>

          <p>
            <strong>Product:</strong> ${product}<br />
            <strong>Quantity:</strong> ${quantity}
          </p>

          <h3>Customer Details</h3>

          <p>
            <strong>Name:</strong> ${name}<br />
            <strong>Phone:</strong> ${phone}<br />
            <strong>WhatsApp:</strong> ${whatsapp || "Not provided"}
          </p>

          <h3>Delivery Details</h3>

          <p>
            <strong>State:</strong> ${state}<br />
            <strong>City:</strong> ${city}<br />
            <strong>Address:</strong> ${address}
          </p>

          ${
            note
              ? `
                <h3>Customer Note</h3>
                <p>${note}</p>
              `
              : ""
          }

          <hr />

          <p>
            <strong>Status:</strong> Pending
          </p>

          <p style="color: #666; font-size: 13px;">
            This notification was automatically generated by the StarnTech Gadget Store.
          </p>

        </div>
      `,
    });

    // =========================
    // SUCCESS
    // =========================

    return res.status(200).json({
      success: true,
      message: "Order submitted successfully.",
    });

  } catch (error) {
    console.error("Order submission error:", error);

    return res.status(500).json({
      success: false,
      message: "Unable to submit your order. Please try again.",
    });
  }
}